[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "polysoleval"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = []

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["--import-mode=importlib"]
